<script setup lang="ts">
import { computed,ref,watch } from 'vue'
import { useRoute } from 'vue-router'
import type { Comparison,Envelope } from '@shared/types'
import { BRAND,PERIODS,PERIOD_LABELS,type Period } from '@shared/config'
import { untoken,vsPath,token } from '@shared/identity'
import { metrics,formatRate } from '@shared/math'
import { api,track } from '../lib/api'
import { saveCard,shareCard } from '../lib/share'
import CompareForm from '../components/CompareForm.vue'
import TrendChart from '../components/TrendChart.vue'
const route=useRoute(),period=ref<Period>(['7d','30d','90d','1y'].includes(String(route.query.period))?route.query.period as Period:'7d'),result=ref<Envelope<Comparison>|null>(null),loading=ref(false),error=ref(''),message=ref('')
const hasPair=computed(()=>!!route.params.keywordA),data=computed(()=>result.value?.data)
let seq=0
async function load(){const id=++seq;result.value=null;error.value='';if(!hasPair.value)return;loading.value=true;try{const a=untoken(String(route.params.keywordA)),b=untoken(String(route.params.keywordB));const r=await api<Envelope<Comparison>>(`/api/vs?a=${encodeURIComponent(a)}&b=${encodeURIComponent(b)}&period=${period.value}`);if(id!==seq)return;result.value=r;document.title=`${r.data.a} vs ${r.data.b} | ${BRAND.name}`;if(r.data.shareA!==null)track('vs_search',{a:r.data.a,b:r.data.b})}catch(e){if(id===seq)error.value=(e as Error).message}finally{if(id===seq)loading.value=false}}
watch([()=>route.params.keywordA,()=>route.params.keywordB,period],load,{immediate:true})
const link=()=>data.value?new URL(vsPath(data.value.a,data.value.b)+`?period=${period.value}`,location.origin).href:location.href
async function share(action:'copy'|'image'|'native'){if(!data.value)return;try{if(action==='copy'){await navigator.clipboard.writeText(link());message.value='링크를 복사했어요.'}else if(action==='image'){await saveCard(data.value,result.value?.meta.mode==='mock');message.value='이미지를 저장했어요.'}else{const blob=await shareCard(data.value,result.value?.meta.mode==='mock'),file=new File([blob],'comparison.png',{type:'image/png'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:document.title,text:link()});else if(navigator.share)await navigator.share({title:document.title,url:link()});else{await navigator.clipboard.writeText(link());message.value='링크를 복사했어요.'}}track('vs_share',{a:data.value.a,b:data.value.b})}catch(e){if((e as Error).name!=='AbortError')message.value='공유하지 못했습니다. 링크 복사나 이미지 저장을 이용해 주세요.'}}
const summaries=computed(()=>data.value?.trend.series.map(s=>({keyword:s.keyword,m7:metrics(s.points,7),m30:metrics(s.points,30)}))??[])
</script>
<template><section class="page-intro"><span class="eyebrow">A LITTLE FRIENDLY COMPETITION</span><h1>관심도, 나란히 비교하기</h1><p>두 키워드를 같은 요청·같은 기간·같은 기준에서 비교합니다.</p></section><CompareForm :key="route.path" :a="data?.a" :b="data?.b"/><template v-if="hasPair"><div class="pills period-selector"><button v-for="p in ['7d','30d','90d','1y'] as const" :key="p" :class="{active:period===p}" @click="period=p;track('period_change')">{{ PERIOD_LABELS[p] }}</button></div><p v-if="loading" class="loading">두 관심사의 흐름을 비교하는 중…</p><p v-if="error" class="alert" role="alert">{{ error }} <button @click="load">다시 시도</button></p><template v-if="data&&result"><p v-if="result.meta.message" class="notice">{{ result.meta.message }}</p><section class="vs-result"><p>{{ PERIOD_LABELS[period] }} · 비교 관심도</p><div class="versus-names"><RouterLink :to="`/search/${token(data.a)}`">{{ data.a }}</RouterLink><span>VS</span><RouterLink :to="`/search/${token(data.b)}`">{{ data.b }}</RouterLink></div><div class="versus-score"><strong>{{ data.shareA??'—' }}</strong><span>:</span><strong>{{ data.shareB??'—' }}</strong></div><div v-if="data.shareA!==null" class="share-bar" role="img" :aria-label="`${data.a} ${data.shareA}, ${data.b} ${data.shareB}`"><div :style="{width:`${data.shareA}%`}"/><div :style="{width:`${data.shareB}%`}"/></div><p v-else>비교할 데이터가 부족하거나 두 대상의 지수가 모두 0입니다.</p><details><summary>이 비율은 무엇인가요?</summary><p>선택한 두 키워드의 NAVER Data Lab 상대 관심도를, 동일 날짜의 평균을 이용해 두 대상 간 비율로 다시 계산한 값입니다. 실제 검색량·시장점유율·선호도 투표가 아닙니다.</p></details><small>{{ data.trend.endDate }}까지 제공된 일간 데이터</small></section><section class="panel"><div class="section-heading"><h2>관심도의 흐름</h2><span class="muted">동일 요청 기준 · 0–100</span></div><TrendChart :series="data.trend.series" :days="PERIODS[period]"/></section><div class="summary-grid"><article v-for="(s,i) in summaries" :key="s.keyword" class="panel"><h3>{{ s.keyword }}</h3><dl><div><dt>최근 7일 변화</dt><dd>{{ formatRate(s.m7) }}</dd></div><div><dt>최근 30일 변화</dt><dd>{{ formatRate(s.m30) }}</dd></div><div><dt>선택 기간 평균 지수</dt><dd>{{ (i?data.metricsB:data.metricsA).currentScore?.toFixed(1)??'미제공' }}</dd></div><div><dt>최고 관심 시점</dt><dd>{{ (i?data.metricsB:data.metricsA).peakDate??'미제공' }}</dd></div></dl></article></div><div v-if="data.shareA!==null" class="share-actions"><button class="primary" @click="share('native')">결과 공유 ↗</button><button class="secondary" @click="share('image')">이미지 저장</button><button class="secondary" @click="share('copy')">링크 복사</button></div><p role="status">{{ message }}</p></template></template><div v-else class="empty"><strong>무엇과 무엇이 궁금한가요?</strong><p>두 대상을 입력하면 기간별 평균, 상승률과 그래프를 확인할 수 있어요.</p></div></template>
