<script setup lang="ts">
import { ref,watch } from 'vue'
import { RouterLink,useRoute } from 'vue-router'
import type { Envelope,Ranking } from '@shared/types'
import { CATEGORIES,SHOP_CATEGORIES,PERIOD_LABELS,type Period } from '@shared/config'
import { formatRate } from '@shared/math'
import { token } from '@shared/identity'
import { api,dateLabel,track } from '../lib/api'
const props=defineProps<{shopping?:boolean;compact?:boolean}>(),emit=defineEmits<{loaded:[count:number]}>()
const period=ref<Period>('7d'),category=ref(String(useRoute().query.category??'전체')),result=ref<Envelope<Ranking[]>|null>(null),loading=ref(false),error=ref('')
let sequence=0
async function load(){const id=++sequence;loading.value=true;error.value='';try{const data=await api<Envelope<Ranking[]>>(`/api/${props.shopping?'shopping':'trends'}?period=${period.value}&category=${encodeURIComponent(category.value)}`);if(id!==sequence)return;result.value=data;emit('loaded',data.data.length)}catch(e){if(id===sequence)error.value=(e as Error).message}finally{if(id===sequence)loading.value=false}}
watch([period,category,()=>props.shopping],load,{immediate:true})
</script>
<template><section class="ranking-section"><div class="section-heading"><div><span class="eyebrow">{{ shopping?'SHOPPING INSIGHT':'RISING INTEREST' }}</span><h2>{{ shopping?'요즘 뭐 사지?':'오늘 발견한 급상승' }}</h2><p>{{ shopping?'쇼핑 클릭 관심도의 변화':'관리 키워드 중 관심도 상승 추이' }}</p></div><RouterLink v-if="compact" :to="shopping?'/shopping':'/trending'" class="text-link">더 보기 ↗</RouterLink></div><div class="toolbar"><div class="pills"><button v-for="p in ['1d','7d','30d','90d'] as const" :key="p" :class="{active:period===p}" :aria-pressed="period===p" @click="period=p;track('period_change')">{{ PERIOD_LABELS[p] }}</button></div><select v-model="category" aria-label="카테고리" @change="track('category_change')"><template v-if="shopping"><option value="전체">전체</option><option v-for="c in SHOP_CATEGORIES" :key="c.id" :value="c.id">{{ c.label }}</option></template><template v-else><option v-for="c in CATEGORIES" :key="c">{{ c }}</option></template></select></div><p class="muted">‘오늘’은 오늘 확인 가능한 최신 일간 데이터입니다.</p><p v-if="error" class="alert" role="alert">{{ error }} <button @click="load">다시 시도</button></p><div v-if="loading" class="loading" aria-live="polite">관심도 흐름을 불러오는 중…</div><template v-else-if="result"><p v-if="result.meta.message" class="notice">{{ result.meta.message }}</p><div v-if="!result.data.length" class="empty"><strong>아직 표시할 상승 데이터가 없습니다.</strong><p>다른 기간을 선택하거나 첫 수집 완료 후 다시 확인해 주세요.</p></div><ol v-else class="ranking-list"><li v-for="(row,i) in result.data.slice(0,compact?5:20)" :key="row.keyword.slug"><RouterLink :to="`/${shopping?'shopping':'search'}/${token(row.keyword.keyword)}`" @click="track(shopping?'shopping_click':'trending_click')"><span class="rank">{{ String(i+1).padStart(2,'0') }}</span><div class="rank-copy"><strong>{{ row.keyword.keyword }}</strong><small>{{ row.keyword.category }} · {{ row.metrics.asOf }} · {{ row.metrics.status==='new'?'기준 기간 관심도 0':'직전 동일 길이 기간 대비' }}</small></div><strong class="positive">↗ {{ formatRate(row.metrics) }}</strong><span class="arrow">→</span></RouterLink></li></ol><p class="updated">{{ dateLabel(result.meta.updatedAt) }} 수집 기준 · {{ shopping?'검색 클릭':'검색' }} 관심도</p></template></section></template>
