import { BRAND } from './config'
export interface ArchiveNews { title:string;url:string;publisher:string;publishedAt:string|null }
export interface ArchiveIssue { id:number;slug:string;title:string;summary:string;firstSeenAt:string;lastSeenAt:string;peakScore:number;peakRank:number;category:string;relatedKeywords:string[];news:ArchiveNews[];updatedAt:string;status:'RAPID'|'RISING'|'STABLE'|'ARCHIVED';currentRank:number|null;scoreModel:'legacy'|'trend7d';legacyPeak:{score?:number;rank?:number} }
export interface ArchiveList {data:ArchiveIssue[];page:number;hasMore:boolean}
export interface ArchiveDetail {data:ArchiveIssue;related:Array<{slug:string;title:string}>}
export const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
export const issuePath=(slug:string)=>`/issue/${encodeURIComponent(slug)}`
export const issueTitle=(issue:ArchiveIssue)=>`${issue.title} 관련 이슈와 뉴스 · 관심도 기록 | ${BRAND.name}`
export const issueDescription=(issue:ArchiveIssue)=>issue.summary.slice(0,240)
const date=(s:string)=>new Date(s).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})
const labels={RAPID:'급상승',RISING:'상승',STABLE:'유지',ARCHIVED:'과거 이슈'}
export function issueBody({data:i,related}:ArchiveDetail){
 return `<article class="archive-page"><a href="/issues">← 이슈 아카이브</a><h1>${esc(i.title)}</h1><p>${labels[i.status]}${i.currentRank?` · 현재 7일 상승 순위 ${i.currentRank}위`:''}</p>${i.status==='ARCHIVED'?'<p class="archive-notice">이 이슈는 현재 실시간 TOP 목록에는 없지만, 과거 TrendPick 또는 이전 왜떠 서비스에서 감지된 이슈입니다.</p>':''}<h2>왜 뜨고 있나요?</h2><p>${esc(i.summary)}</p><p class="archive-note">관심도는 상대 지수입니다. 사건의 인과관계나 절대 검색 횟수를 의미하지 않습니다.</p><dl><dt>처음 감지</dt><dd>${esc(date(i.firstSeenAt))}</dd><dt>마지막 감지</dt><dd>${esc(date(i.lastSeenAt))}</dd><dt>최고 순위</dt><dd>${i.peakRank}위</dd><dt>최고 점수</dt><dd>${i.peakScore} (${i.scoreModel==='legacy'?'이전 왜떠':'7일 상승 점수'})</dd></dl>${i.legacyPeak.rank?`<p>이전 왜떠 최고 기록: ${i.legacyPeak.rank}위 · ${i.legacyPeak.score}점</p>`:''}<p class="archive-note">최고 기록은 수집 시점의 관리 키워드 목록 기준입니다. 이전 왜떠 기록은 현재 점수와 계산 방식이 다릅니다.</p><h2>관련 뉴스</h2>${i.news.length?`<ul>${i.news.filter(n=>/^https?:\/\//i.test(n.url)).map(n=>`<li><a href="${esc(n.url)}" target="_blank" rel="noopener noreferrer">${esc(n.title)}</a><small>${esc(n.publisher)}${n.publishedAt?' · '+esc(n.publishedAt.slice(0,10)):''}</small></li>`).join('')}</ul>`:'<p>보관된 대표 뉴스가 없습니다. 아래 관심도 분석에서 현재 관련 콘텐츠를 확인할 수 있습니다.</p>'}<h2>관련 키워드</h2><p>${i.relatedKeywords.length?i.relatedKeywords.map(esc).join(' · '):'확인된 별칭이 없습니다.'}</p><h2>관련 이슈</h2><p class="archive-note">같은 카테고리에서 감지된 기록입니다. 동일 사건이라는 의미는 아닙니다.</p><ul>${related.map(r=>`<li><a href="${issuePath(r.slug)}">${esc(r.title)}</a></li>`).join('')||'<li>같은 카테고리의 다른 기록이 없습니다.</li>'}</ul><a href="/search/${encodeURIComponent(i.title)}">현재 관심도 분석 보기 →</a></article>`
}
export function listBody(list:ArchiveList){return `<section class="archive-page"><h1>이슈 아카이브</h1><p>실시간 목록에서 사라져도 관심도 기록과 대표 뉴스는 보관합니다.</p><ul>${list.data.map(i=>`<li><a href="${issuePath(i.slug)}">${esc(i.title)}</a><p>${esc(i.summary)}</p><small>마지막 감지 ${esc(date(i.lastSeenAt))}</small></li>`).join('')||'<li>아직 보관된 이슈가 없습니다. 수집이 완료되면 표시됩니다.</li>'}</ul><nav>${list.page>1?`<a href="/issues?page=${list.page-1}">이전</a>`:''} ${list.hasMore?`<a href="/issues?page=${list.page+1}">다음</a>`:''}</nav></section>`}
export function archiveDocument(title:string,description:string,canonical:string,body:string,index=true){const origin=new URL(canonical).origin;return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${index?'index,follow':'noindex,follow'}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}"><meta property="og:type" content="article"><meta property="og:image" content="${esc(origin)}/og.png"><link rel="canonical" href="${esc(canonical)}"><link rel="stylesheet" href="/archive.css"></head><body><header class="archive-header"><a href="/">${esc(BRAND.name)}</a><nav><a href="/trending">급상승</a><a href="/vs">A vs B</a><a href="/issues">이슈 아카이브</a></nav></header><main>${body}</main><footer class="archive-page"><a href="/methodology">계산 방법</a> · <a href="/privacy">개인정보처리방침</a> · <a href="/terms">이용약관</a></footer><!-- Cloudflare Web Analytics --><script type='module' src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "9665a3469374432ea9cbe09b77b9cb19"}'></script><!-- End Cloudflare Web Analytics --></body></html>`}
